### ISSUE TITLE
Initial BOM review

### ISSUE THREAD

**Issue by timChase98** [jproulx1/388-Pedometer#1]
Hey Joshua,
   This actually looks pretty good in terms of formating.  I think you may be missing some of the necessary components for your design though.  I don't see a display or an accelerometer.  You may also want to take a look at the reference implementations in the datasheet for the 328pb

**Comment by jproulx1** [comment]
The exact display viall told me we would be using is on aliexpress, want me to include that in the next iteration? I was looking at an arduino nano schematic as a reference for the various 328p parts, are we using the pb?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timChase98** [comment]
Yes we are using the 328pb not the p.  I realize that when I sent out the directions for the BOM i forgot to add an alternative supplier column for specialty items like Displays.  I'm in the process of getting them ordered so I'll update the 211 stock sheet with that information accordingly when I get a chance.

**Comment by jproulx1** [comment]
@timChase98 I have updated the BOM

**Comment by jproulx1** [comment]
@timChase98 Updated the csv to be comma separated (which in hindsight makes sense with a comma separated value file)
